<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cairo</string>
	</array>
	<key>name</key>
	<string>Cairo</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#directives</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#statements</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>class-instance</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[[:upper:]][_$[:alnum:]]+[[:lower:]]+[_$[:alnum:]]+</string>
					<key>name</key>
					<string>support.class.cairo</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>#</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>comment.line.number-sign</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>TODO</string>
							<key>name</key>
							<string>comment.line.number-sign</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>declaration</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#import</string>
				</dict>
			</array>
		</dict>
		<key>directives</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.directive.cairo</string>
						</dict>
					</dict>
					<key>end</key>
					<string></string>
					<key>match</key>
					<string>(?&lt;!\w)\s*(%builtins|%lang)\s+</string>
				</dict>
			</array>
		</dict>
		<key>expression</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#expression-without-identifiers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#identifiers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#expression-punctuations</string>
				</dict>
			</array>
		</dict>
		<key>expression-operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\%\{|\%\}</string>
					<key>name</key>
					<string>keyword.brackets.python-hints.cairo</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(=|!|&gt;|&lt;|\||&amp;|\?|\^|~|\*|\+|\-|\/|\%)</string>
					<key>name</key>
					<string>keyword.operator</string>
					<key>omment</key>
					<string>Operators</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;![\w$])(cast)(?![\w$])</string>
					<key>name</key>
					<string>keyword.operator.cast.cairo</string>
				</dict>
			</array>
		</dict>
		<key>expression-punctuations</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#punctuation-accessor</string>
				</dict>
			</array>
		</dict>
		<key>expression-without-identifiers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function-expression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#storages</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#parameters</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#expression-operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function-call</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#support-objects</string>
				</dict>
			</array>
		</dict>
		<key>function-call</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>([_$[:alpha:]][_$[:alnum:]]+)\s*(?=\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.cairo</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?&lt;=\))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#literal</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#identifiers</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#expression-operators</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>function-expression</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(func)\s+([_$[:alpha:]][_$[:alnum:]]*)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.function.cairo</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.cairo</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?&lt;=:)</string>
					<key>name</key>
					<string>meta.function.expression.cairo</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#function-implicit</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#function-params</string>
						</dict>
						<dict>
							<key>match</key>
							<string>-&gt;</string>
							<key>name</key>
							<string>keyword.function.return.cairo</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>function-implicit</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\{</string>
					<key>end</key>
					<string>\}</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#parameters</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>function-params</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>end</key>
					<string>\)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#parameters</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>identifiers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;!\w)([[:upper:]][_$[:digit:][:upper:]]*)(?![_$[:alnum:]])</string>
					<key>name</key>
					<string>variable.other.constant.cairo</string>
				</dict>
			</array>
		</dict>
		<key>import</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;!\w)\s*(from)\s</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.declaration.cairo</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\s*(import)\s</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.declaration.cairo</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#punctuation-accessor</string>
						</dict>
						<dict>
							<key>match</key>
							<string>[_$[:alpha:]][_$[:alnum:]]+</string>
							<key>name</key>
							<string>meta.import.from.location.cairo</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(else|if|in|return|end|assert)\b</string>
					<key>name</key>
					<string>keyword.controls.cairo</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(from|import|func|namespace)\b</string>
					<key>name</key>
					<string>keyword.declaration.cairo</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^\s*@(constructor|storage_var|view|external|contract_interface|known_ap_change|event)\s+</string>
					<key>name</key>
					<string>keyword.others.cairo</string>
				</dict>
			</array>
		</dict>
		<key>literal</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#numeric-literal</string>
				</dict>
			</array>
		</dict>
		<key>numeric-literal</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?:([0-9]+)|(0x[0-9a-fA-F]+))\b</string>
					<key>name</key>
					<string>constant.numeric.decimal.cairo</string>
				</dict>
			</array>
		</dict>
		<key>parameters</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#punctuation-accessor</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.type.cairo</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(:)\s*([_$[:alpha:]][_$[:alnum:]]+)</string>
				</dict>
			</array>
		</dict>
		<key>punctuation-accessor</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.dot-accessor.cairo</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\.)|(\*)</string>
				</dict>
			</array>
		</dict>
		<key>punctuation-semicolon</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>;</string>
					<key>name</key>
					<string>punctuation.terminator.statement.cairo</string>
				</dict>
			</array>
		</dict>
		<key>statements</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#declaration</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#punctuation-semicolon</string>
				</dict>
			</array>
		</dict>
		<key>storages</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(let|const|local|struct|member|alloc_locals)\b</string>
					<key>name</key>
					<string>storage.type.cairo</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.cairo</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.cairo</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.cairo</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.cairo</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.cairo</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.cairo</string>
				</dict>
			</array>
		</dict>
		<key>support-objects</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#class-instance</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.cairo</string>
	<key>uuid</key>
	<string>ad87d2cd-8575-4bfe-984e-9421a3788912</string>
</dict>
</plist>
